                                                                                                                                               ddl                                                                                                                                               
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 -- analytics.get_sales_category_mix                                                                                                                                                                                                                                                            +
 CREATE OR REPLACE FUNCTION analytics.get_sales_category_mix(p_asof timestamp with time zone, p_window text, p_location uuid)                                                                                                                                                                   +
  RETURNS TABLE(category text, revenue numeric, share_pct numeric)                                                                                                                                                                                                                              +
  LANGUAGE sql                                                                                                                                                                                                                                                                                  +
 AS $function$                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                +
 with params as (                                                                                                                                                                                                                                                                               +
   select                                                                                                                                                                                                                                                                                       +
     date(p_asof) as as_of_day,                                                                                                                                                                                                                                                                 +
     case                                                                                                                                                                                                                                                                                       +
       when p_window = '7d' then 7                                                                                                                                                                                                                                                              +
       when p_window = '30d' then 30                                                                                                                                                                                                                                                            +
       when p_window = '90d' then 90                                                                                                                                                                                                                                                            +
       when p_window = 'ytd' then extract(doy from date(p_asof))::int                                                                                                                                                                                                                           +
       else 30                                                                                                                                                                                                                                                                                  +
     end as win_days                                                                                                                                                                                                                                                                            +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 filtered as (                                                                                                                                                                                                                                                                                  +
   select *                                                                                                                                                                                                                                                                                     +
   from raw.sales_line_items r, params p                                                                                                                                                                                                                                                        +
   where r.business_date > p.as_of_day - p.win_days                                                                                                                                                                                                                                             +
     and r.business_date <= p.as_of_day                                                                                                                                                                                                                                                         +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 agg as (                                                                                                                                                                                                                                                                                       +
   select                                                                                                                                                                                                                                                                                       +
     category,                                                                                                                                                                                                                                                                                  +
     sum(net_sales) as revenue                                                                                                                                                                                                                                                                  +
   from filtered                                                                                                                                                                                                                                                                                +
   group by category                                                                                                                                                                                                                                                                            +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 total as (                                                                                                                                                                                                                                                                                     +
   select sum(revenue) as total_rev from agg                                                                                                                                                                                                                                                    +
 )                                                                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                                                +
 select                                                                                                                                                                                                                                                                                         +
   a.category,                                                                                                                                                                                                                                                                                  +
   a.revenue,                                                                                                                                                                                                                                                                                   +
   round(a.revenue / t.total_rev * 100,2) as share_pct                                                                                                                                                                                                                                          +
 from agg a, total t                                                                                                                                                                                                                                                                            +
 order by revenue desc;                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                                +
                                                                                                                                                                                                                                                                                                +
 
 -- analytics.get_sales_channel_mix                                                                                                                                                                                                                                                             +
 CREATE OR REPLACE FUNCTION analytics.get_sales_channel_mix(p_asof timestamp with time zone, p_window text, p_location uuid)                                                                                                                                                                    +
  RETURNS TABLE(order_channel text, revenue numeric, share_pct numeric)                                                                                                                                                                                                                         +
  LANGUAGE sql                                                                                                                                                                                                                                                                                  +
 AS $function$                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                +
 with params as (                                                                                                                                                                                                                                                                               +
   select                                                                                                                                                                                                                                                                                       +
     date(p_asof) as as_of_day,                                                                                                                                                                                                                                                                 +
     case                                                                                                                                                                                                                                                                                       +
       when p_window = '7d' then 7                                                                                                                                                                                                                                                              +
       when p_window = '30d' then 30                                                                                                                                                                                                                                                            +
       when p_window = '90d' then 90                                                                                                                                                                                                                                                            +
       when p_window = 'ytd' then extract(doy from date(p_asof))::int                                                                                                                                                                                                                           +
       else 30                                                                                                                                                                                                                                                                                  +
     end as win_days                                                                                                                                                                                                                                                                            +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 filtered as (                                                                                                                                                                                                                                                                                  +
   select *                                                                                                                                                                                                                                                                                     +
   from raw.sales_line_items r, params p                                                                                                                                                                                                                                                        +
   where r.business_date > p.as_of_day - p.win_days                                                                                                                                                                                                                                             +
     and r.business_date <= p.as_of_day                                                                                                                                                                                                                                                         +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 agg as (                                                                                                                                                                                                                                                                                       +
   select                                                                                                                                                                                                                                                                                       +
     order_channel,                                                                                                                                                                                                                                                                             +
     sum(net_sales) as revenue                                                                                                                                                                                                                                                                  +
   from filtered                                                                                                                                                                                                                                                                                +
   group by order_channel                                                                                                                                                                                                                                                                       +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 total as (                                                                                                                                                                                                                                                                                     +
   select sum(revenue) as total_rev from agg                                                                                                                                                                                                                                                    +
 )                                                                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                                                +
 select                                                                                                                                                                                                                                                                                         +
   a.order_channel,                                                                                                                                                                                                                                                                             +
   a.revenue,                                                                                                                                                                                                                                                                                   +
   round(a.revenue / t.total_rev * 100,2) as share_pct                                                                                                                                                                                                                                          +
 from agg a, total t                                                                                                                                                                                                                                                                            +
 order by revenue desc;                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                                +
                                                                                                                                                                                                                                                                                                +
 
 -- analytics.get_sales_kpis_delta                                                                                                                                                                                                                                                              +
 CREATE OR REPLACE FUNCTION analytics.get_sales_kpis_delta(p_asof timestamp with time zone, p_window text, p_location uuid)                                                                                                                                                                     +
  RETURNS TABLE(as_of_ts timestamp with time zone, revenue numeric, revenue_delta_pct numeric, orders integer, orders_delta_pct numeric, aov numeric, aov_delta_pct numeric, gross_margin_pct numeric, gross_margin_delta_pp numeric, discount_rate_pct numeric, discount_rate_delta_pp numeric)+
  LANGUAGE sql                                                                                                                                                                                                                                                                                  +
 AS $function$                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                +
 with params as (                                                                                                                                                                                                                                                                               +
   select                                                                                                                                                                                                                                                                                       +
     date(p_asof) as as_of_day,                                                                                                                                                                                                                                                                 +
     case                                                                                                                                                                                                                                                                                       +
       when p_window = '7d' then 7                                                                                                                                                                                                                                                              +
       when p_window = '30d' then 30                                                                                                                                                                                                                                                            +
       when p_window = '90d' then 90                                                                                                                                                                                                                                                            +
       when p_window = 'ytd' then extract(doy from date(p_asof))::int                                                                                                                                                                                                                           +
       else 30                                                                                                                                                                                                                                                                                  +
     end as win_days                                                                                                                                                                                                                                                                            +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 current_window as (                                                                                                                                                                                                                                                                            +
   select *                                                                                                                                                                                                                                                                                     +
   from raw.sales_line_items r, params p                                                                                                                                                                                                                                                        +
   where r.business_date > p.as_of_day - p.win_days                                                                                                                                                                                                                                             +
     and r.business_date <= p.as_of_day                                                                                                                                                                                                                                                         +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 previous_window as (                                                                                                                                                                                                                                                                           +
   select *                                                                                                                                                                                                                                                                                     +
   from raw.sales_line_items r, params p                                                                                                                                                                                                                                                        +
   where r.business_date > p.as_of_day - (p.win_days*2)                                                                                                                                                                                                                                         +
     and r.business_date <= p.as_of_day - p.win_days                                                                                                                                                                                                                                            +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 agg_current as (                                                                                                                                                                                                                                                                               +
   select                                                                                                                                                                                                                                                                                       +
     round(sum(net_sales),2) as revenue,                                                                                                                                                                                                                                                        +
     sum(quantity)::int as orders,                                                                                                                                                                                                                                                              +
     round(sum(discount_amount),2) as discount,                                                                                                                                                                                                                                                 +
     round(sum(gross_sales),2) as gross_sales                                                                                                                                                                                                                                                   +
   from current_window                                                                                                                                                                                                                                                                          +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 agg_previous as (                                                                                                                                                                                                                                                                              +
   select                                                                                                                                                                                                                                                                                       +
     round(sum(net_sales),2) as revenue,                                                                                                                                                                                                                                                        +
     sum(quantity)::int as orders,                                                                                                                                                                                                                                                              +
     round(sum(discount_amount),2) as discount,                                                                                                                                                                                                                                                 +
     round(sum(gross_sales),2) as gross_sales                                                                                                                                                                                                                                                   +
   from previous_window                                                                                                                                                                                                                                                                         +
 )                                                                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                                                +
 select                                                                                                                                                                                                                                                                                         +
   p_asof,                                                                                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                                                                +
   c.revenue,                                                                                                                                                                                                                                                                                   +
   case when p.revenue = 0 then null                                                                                                                                                                                                                                                            +
        else round((c.revenue - p.revenue)/p.revenue*100,2)                                                                                                                                                                                                                                     +
   end,                                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                +
   c.orders,                                                                                                                                                                                                                                                                                    +
   case when p.orders = 0 then null                                                                                                                                                                                                                                                             +
        else round((c.orders - p.orders)::numeric/p.orders*100,2)                                                                                                                                                                                                                               +
   end,                                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                +
   case when c.orders=0 then null else round(c.revenue/c.orders,2) end,                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                +
   case when p.orders=0 then null                                                                                                                                                                                                                                                               +
        else round(                                                                                                                                                                                                                                                                             +
             ((c.revenue/c.orders)-(p.revenue/p.orders))                                                                                                                                                                                                                                        +
             /(p.revenue/p.orders)*100,2)                                                                                                                                                                                                                                                       +
   end,                                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                +
   67::numeric, -- margin stays from daily table for now                                                                                                                                                                                                                                        +
   0::numeric,                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                +
   case when c.gross_sales=0 then null                                                                                                                                                                                                                                                          +
        else round(c.discount/c.gross_sales*100,2)                                                                                                                                                                                                                                              +
   end,                                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                +
   case when p.gross_sales=0 then null                                                                                                                                                                                                                                                          +
        else round(                                                                                                                                                                                                                                                                             +
             (c.discount/c.gross_sales*100)                                                                                                                                                                                                                                                     +
             - (p.discount/p.gross_sales*100),2)                                                                                                                                                                                                                                                +
   end                                                                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                                                                                +
 from agg_current c cross join agg_previous p;                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                                +
                                                                                                                                                                                                                                                                                                +
 
 -- analytics.get_sales_timeseries_daily                                                                                                                                                                                                                                                        +
 CREATE OR REPLACE FUNCTION analytics.get_sales_timeseries_daily(p_asof timestamp with time zone, p_window text, p_location uuid)                                                                                                                                                               +
  RETURNS TABLE(day date, revenue numeric, orders integer, aov numeric, gross_margin_pct numeric, discount_rate_pct numeric)                                                                                                                                                                    +
  LANGUAGE sql                                                                                                                                                                                                                                                                                  +
 AS $function$                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                +
 with params as (                                                                                                                                                                                                                                                                               +
   select                                                                                                                                                                                                                                                                                       +
     date(p_asof) as as_of_day,                                                                                                                                                                                                                                                                 +
     case                                                                                                                                                                                                                                                                                       +
       when p_window = '7d' then 7                                                                                                                                                                                                                                                              +
       when p_window = '30d' then 30                                                                                                                                                                                                                                                            +
       when p_window = '90d' then 90                                                                                                                                                                                                                                                            +
       when p_window = 'ytd' then extract(doy from date(p_asof))::int                                                                                                                                                                                                                           +
       else 30                                                                                                                                                                                                                                                                                  +
     end as win_days                                                                                                                                                                                                                                                                            +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 filtered as (                                                                                                                                                                                                                                                                                  +
   select r.*                                                                                                                                                                                                                                                                                   +
   from restaurant.raw_restaurant_daily r, params p                                                                                                                                                                                                                                             +
   where r.day > p.as_of_day - p.win_days                                                                                                                                                                                                                                                       +
     and r.day <= p.as_of_day                                                                                                                                                                                                                                                                   +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 daily as (                                                                                                                                                                                                                                                                                     +
   select                                                                                                                                                                                                                                                                                       +
     day,                                                                                                                                                                                                                                                                                       +
     sum(revenue) as revenue,                                                                                                                                                                                                                                                                   +
     sum(orders) as orders,                                                                                                                                                                                                                                                                     +
     sum(cogs) as cogs                                                                                                                                                                                                                                                                          +
   from filtered                                                                                                                                                                                                                                                                                +
   group by day                                                                                                                                                                                                                                                                                 +
 )                                                                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                                                +
 select                                                                                                                                                                                                                                                                                         +
   day,                                                                                                                                                                                                                                                                                         +
   revenue,                                                                                                                                                                                                                                                                                     +
   orders,                                                                                                                                                                                                                                                                                      +
   case when orders = 0 then null else round(revenue/orders,2) end as aov,                                                                                                                                                                                                                      +
   case when revenue = 0 then null else round((revenue - cogs)/revenue*100,2) end as gross_margin_pct,                                                                                                                                                                                          +
   0::numeric as discount_rate_pct                                                                                                                                                                                                                                                              +
 from daily                                                                                                                                                                                                                                                                                     +
 order by day;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                                +
                                                                                                                                                                                                                                                                                                +
 
 -- analytics.get_sales_top_items                                                                                                                                                                                                                                                               +
 CREATE OR REPLACE FUNCTION analytics.get_sales_top_items(p_asof timestamp with time zone, p_window text, p_location uuid, p_limit integer)                                                                                                                                                     +
  RETURNS TABLE(item_name text, quantity bigint, revenue numeric, share_pct numeric)                                                                                                                                                                                                            +
  LANGUAGE sql                                                                                                                                                                                                                                                                                  +
 AS $function$                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                +
 with params as (                                                                                                                                                                                                                                                                               +
   select                                                                                                                                                                                                                                                                                       +
     date(p_asof) as as_of_day,                                                                                                                                                                                                                                                                 +
     case                                                                                                                                                                                                                                                                                       +
       when p_window = '7d' then 7                                                                                                                                                                                                                                                              +
       when p_window = '30d' then 30                                                                                                                                                                                                                                                            +
       when p_window = '90d' then 90                                                                                                                                                                                                                                                            +
       when p_window = 'ytd' then extract(doy from date(p_asof))::int                                                                                                                                                                                                                           +
       else 30                                                                                                                                                                                                                                                                                  +
     end as win_days                                                                                                                                                                                                                                                                            +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 filtered as (                                                                                                                                                                                                                                                                                  +
   select *                                                                                                                                                                                                                                                                                     +
   from raw.sales_line_items r, params p                                                                                                                                                                                                                                                        +
   where r.business_date > p.as_of_day - p.win_days                                                                                                                                                                                                                                             +
     and r.business_date <= p.as_of_day                                                                                                                                                                                                                                                         +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 agg as (                                                                                                                                                                                                                                                                                       +
   select                                                                                                                                                                                                                                                                                       +
     item_name,                                                                                                                                                                                                                                                                                 +
     sum(quantity) as quantity,                                                                                                                                                                                                                                                                 +
     sum(net_sales) as revenue                                                                                                                                                                                                                                                                  +
   from filtered                                                                                                                                                                                                                                                                                +
   group by item_name                                                                                                                                                                                                                                                                           +
 ),                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                +
 total as (                                                                                                                                                                                                                                                                                     +
   select sum(revenue) as total_rev from agg                                                                                                                                                                                                                                                    +
 )                                                                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                                                +
 select                                                                                                                                                                                                                                                                                         +
   a.item_name,                                                                                                                                                                                                                                                                                 +
   a.quantity,                                                                                                                                                                                                                                                                                  +
   a.revenue,                                                                                                                                                                                                                                                                                   +
   round(a.revenue / t.total_rev * 100,2) as share_pct                                                                                                                                                                                                                                          +
 from agg a, total t                                                                                                                                                                                                                                                                            +
 order by revenue desc                                                                                                                                                                                                                                                                          +
 limit p_limit;                                                                                                                                                                                                                                                                                 +
                                                                                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                                +
                                                                                                                                                                                                                                                                                                +
 
(5 rows)

